project:
  type: website

website:
  title: "Psychology Statistics Demos"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: single_sample.qmd
        text: "1. Single Sample"
      - href: sampling.qmd
        text: "2. Sampling Distributions"
      - href: ind_samples.qmd
        text: "3. Independent Samples"

format:
  html:
    theme: cosmo
    resources: 
      - shinylive-sw.js
filters:
  - shinylive
